FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /backend

# apt-getのアップデート、apt-get updateで使用されたパッケージリストのキャッシュをクリーンアップ
RUN apt-get update \
    && rm -rf /var/lib/apt/lists/*  

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


# CMD ["uvicorn", "src.app:app", "--reload", "--host", "0.0.0.0", "--port", "8100"]
